services:

  backend:
    build:
      context: ./backend
    container_name: inventory-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always


  frontend:
    build:
      context: ./frontend
    container_name: inventory-frontend
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always