"""your migration message

Revision ID: 1185f9803a3d
Revises: 001
Create Date: 2026-06-19 00:26:41.901970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1185f9803a3d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
